// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-LbuP3YeOaAU-s1B97SgXSNgt_k7bhAM',
    appId: '1:282254413211:web:d21ea504247b3cc26a653e',
    messagingSenderId: '282254413211',
    projectId: 'loginapp-72ece',
    authDomain: 'loginapp-72ece.firebaseapp.com',
    storageBucket: 'loginapp-72ece.appspot.com',
    measurementId: 'G-PHC0YV4MXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkFXYgpFqxgRJ-wwHAPwnTvNCLjm0t3kU',
    appId: '1:282254413211:android:15d85ae07982503b6a653e',
    messagingSenderId: '282254413211',
    projectId: 'loginapp-72ece',
    storageBucket: 'loginapp-72ece.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrMbprJxmQnpoZz3iKF2YTiBCSpS5OWnk',
    appId: '1:282254413211:ios:6dacf57d6dfc713a6a653e',
    messagingSenderId: '282254413211',
    projectId: 'loginapp-72ece',
    storageBucket: 'loginapp-72ece.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrMbprJxmQnpoZz3iKF2YTiBCSpS5OWnk',
    appId: '1:282254413211:ios:6dacf57d6dfc713a6a653e',
    messagingSenderId: '282254413211',
    projectId: 'loginapp-72ece',
    storageBucket: 'loginapp-72ece.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-LbuP3YeOaAU-s1B97SgXSNgt_k7bhAM',
    appId: '1:282254413211:web:c3d2850e7a84845a6a653e',
    messagingSenderId: '282254413211',
    projectId: 'loginapp-72ece',
    authDomain: 'loginapp-72ece.firebaseapp.com',
    storageBucket: 'loginapp-72ece.appspot.com',
    measurementId: 'G-9XKW4XY9ZC',
  );
}
